server:
  port: 8081
  address: 0.0.0.0
spring:

  datasource:
    url: jdbc:postgresql://sqlcont:5432/tracker-db
    username: tracker-user
    password: tracker-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml


jwt:
  secret: v6b+8X0O8zIYFhG4u8n5nJ3hK0x9m9QWm6H6xE9f0u=I
  expiration: 86400000 # 24h

logging:
  level:
    root: INFO
    com.poptsov: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE